<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1**

Subsetting: refers to selecting elements from a specific portion of a data set

Indexing: refers to selecting one element

Slicing: refers to selecting a range of elements

Masking: involves the creation of a boolean array or data structure that is used to select certain elements from another array or dataset.

**Exercise 2**

In [1]:
import numpy as np

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [3]:
array_of_num = np_array_2d[:, 0]

In [4]:
newarr = array_of_num.astype(int)

In [5]:
newarr

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [6]:
even_odd_array = newarr%2

In [7]:
even_odd_array

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [12]:
true_false_array = even_odd_array == 1

In [13]:
true_false_array

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [16]:
np_array_2d[true_false_array][:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')