<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

We are learning Python as a tool to help us understand science and solve problems related to science. To do this, we must interact with information/data and transform them to yield a solution. For this, it is essential to have ways to store and manipulate data easily and efficiently beyond the simple variables we have encountered so far. Python offers a variety of ways to store and manipulate data. You have already met the **list** and **dictionary** in a previous chapter. However, there are several more; here is a (non-comprehensive) list.

1. Lists
2. Numpy arrays
3. Dictionaries
4. Tuples
5. Dataframes
6. Classes

In these chapters on basics, I will only discuss Python **lists**, Numpy **arrays**, **dictionaries** and **tuples**. If you want to learn about **dataframes** please look at the Data Processing basket in the Applications part. **Classes** are an advanced topic that I will touch on in the Nice chapter.

**Important**:

It is very important to understand how to store, retrieve and modify data in programming. This is because these abstract structures will **influence how you think about data<sup>1</sup>**. This will ultimately aid (or hinder) your ability to conjure up algorithms to solve problems.



# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Here is how to store the same information (in this case, some superhero data) using <font color='orange'>lists</font>, <font color='orange'>arrays</font> and <font color='orange'>dictionaries</font>.

**Python Lists**

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Arrays**

In [3]:
import numpy as np

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

Notice:

- Dictionaries use a key and an associated value separated by a `:`
- The dictionary very elegantly holds the real and superhero names in one structure while we need two lists (or arrays) for the same data.
- For lists and arrays, the order matters. I.e. ‘Iron Man’ must be in the same position as ‘Tony Stark’ for things to work.

Lists (and arrays) offer many features that dictionaries don’t and vice versa. Which data storage strategy to choose will depend on the problem you are trying to solve.

**Remember**:

There are three basic ways of storing data:
1. lists,
2. NumPy arrays and
3. dictionaries.

- `py` and `np` is added in front of the variable for clarity. You can choose any name for the variables (provided that they are not a Python keyword like `for`, `if`).
- When I say ‘arrays’, I mean ‘NumPy arrays’, and when I say ‘lists’, I mean ‘Python lists’.

## 1.2 Accessing data from a list (or array)

To access data from lists (and arrays), we need to use an index corresponding to the data’s position. Python is a zero-indexed language, meaning it starts counting at 0. So if you want to access a particular element in the list (or array), you need to specify the relevant index starting from zero. The image below shows the relationship between the position and index.

![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Example 1**

In [7]:
py_real_names[0]

'Natasha Romanoff'

**Example 2**

In [8]:
py_super_names[0]

'Black Widow'

**Example 3**

Using a negative index allows us to count from the back of the list. For instance, using the index -1 will give the last element. This is super useful because we can easily access the last element without knowing the list size.

In [9]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [10]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

**Remember**

Data in lists (and arrays) must be accessed using a zero-based index.

## 1.3 Accessing data from a dictionary

Dictionaries hold data (values) paired with a key. i.e. you can access the value (in this case, the superhero name) using the real name as a key. Here is how it works:

In [11]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

**Remember**

Dictionaries have a key-value structure.

If you want, you can access all the keys and all the values as follows:

In [14]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [15]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

Unlike with a dictionary, we needed two lists to store the corresponding real and superhero names. An obvious way around the need to have two lists is to have a 2D list (or array) as follows.

In [16]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

Lists and arrays have some similarities but more differences. It is important to know these to make full use of these differences. Here are a few quick examples of using lists and arrays. These will allow you to appreciate the versatility that each offers.

## 2.1 Size

Often, you need to know how many elements there are in lists or arrays. We can use the `len()` function for this purpose for both lists and arrays. However, arrays also offer other options.

In [73]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [74]:
len(py_list_2d)

10

In [75]:
len(np_array_2d)

10

In [18]:
np_array_2d.shape

(10, 2)

Notice the absence of brackets `( )` in `shape` above. This is because `shape` is **not** a function. Instead, it is a property or <font color='orange'>attribute</font> of the NumPy array. 

## 2.2 Arrays are fussy about type

Please recall the previous discussion about data types (e.g., int, float, str). One prominent difference between lists and arrays is that arrays insist on having only a single data type; lists are more accommodating. Consider the following example and notice how the numbers are converted to English (`' '`) when we create the NumPy array.

In [31]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [32]:
#Lists
py_list

[1, 1.5, 'A']

In [33]:
#Arrays
np_array

array(['1', '1.5', 'A'], dtype='<U32')

When dealing with datasets with both numbers and text, you must be mindful of this restriction. However, this is just an annoyance and not a problem as we can easily change type (typecast) using the ‘hidden’ function `astypes()`. More about this in a later chapter. For the moment,

**Remember**

NumPy arrays tolerate only a single type.

## 2.3 Adding a number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [25]:
#Array

np_array + 10

array([11, 12, 13, 14, 15])

In [24]:
#Lists

py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [36]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [37]:
#Lists
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [38]:
#Arrays
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

So, adding lists causes them to grow while adding arrays is an element-wise operation.

## 2.5 Multiplying by a Number

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [40]:
#Lists
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
#Arrays
np_array*2

array([ 2,  4,  6,  8, 10])

So multiplying by a number makes a list grow, whereas an array multiplies its elements by the number!

## 2.6 Squaring

In [42]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [43]:
#Arrays
np_array**2

array([ 1,  4,  9, 16, 25])

In [44]:
#Lists
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [68]:
#Lists example 1
py_list == 3     # The question is whether py_list has the same value as the integer 3 

False

In [50]:
#Lists example 2
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [69]:
#Arrays example 1
np_array == 3  #The question is checking if each element in the array has the same value as the integer 3.

array([False, False,  True, False, False])

In [70]:
#Arrays example 2
np_array > 3  # The question is asking if each element in the array is greater than the integer 3.

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [57]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [59]:
#Lists
sum(py_list)     # sum() is a base Python function

15

In [60]:
max(py_list)     # max() is a base Python function

5

In [61]:
min(py_list)     # min() is a base Python function

1

In [62]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [63]:
#Arrays
np_array.sum()

15

In [64]:
np_array.max()

5

In [65]:
np_array.min()

1

In [66]:
np_array.mean()

3.0

In [67]:
np_array.std()

1.4142135623730951

**Remember** 

(**roughly speaking**) an operation on a list works on the **whole** list. In contrast, an operation on an array works on the **individual elements** of the array.

# Exercises & Self-Assessment

In [71]:



# Exercises answers are in the respective notebooks.




## Footnotes

1. For example, think of how easy it is to do row or column manipulations of data when put into a spreadsheet format